#!/usr/bin/env python3
"""
Fetch Commons / Flickr Commons Images (CLI)
===========================================

Thin command-line wrapper over `core.commons_imagery`, which holds the actual
pipeline (also used by the research-worker handler
`research_worker/handlers/commons.py`). This script adds argument parsing,
human-readable reporting, JSON/SQL emit, and the dry-run / no-DB conveniences
used for review.

LICENSE POLICY (default): the free-culture set -- PD, CC0, CC-BY, CC-BY-SA.
NonCommercial (NC) and NoDerivatives (ND) variants are always rejected. Narrow
with `--licenses public_domain,cc0` for an attribution-free set.

USAGE
-----
    # Dry run, review candidates + export JSON/SQL, no DB writes:
    python fetch_commons_images.py --name "Dave Brubeck" --dry-run --visual \
        --emit-json out/brubeck.json --emit-sql out/brubeck.sql

    # Gather + write to DB:
    python fetch_commons_images.py --name "Dave Brubeck" --visual

    # Pure gather, no DB (supply a UUID so emitted SQL/JSON can link):
    python fetch_commons_images.py --name "Dave Brubeck" --no-db \
        --performer-id 00000000-0000-0000-0000-000000000000 --emit-sql out/x.sql
"""

import json
import logging
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))
from script_base import ScriptBase, run_script  # noqa: E402

from db_utils import (  # noqa: E402
    find_performer_by_name, find_performer_by_id, get_performer_images,
    normalize_apostrophes,
)
from core import commons_imagery as ci  # noqa: E402

logger = logging.getLogger("fetch_commons_images")


# ---------------------------------------------------------------------------
# Reference image (identity) — DB-side resolution lives here, not in the module
# ---------------------------------------------------------------------------

def _reference_urls(performer: Dict[str, Any], explicit: Optional[str],
                    no_db: bool, identity: bool) -> List[str]:
    if not identity:
        return []
    if explicit:
        return [explicit]
    if no_db:
        return []
    try:
        imgs = get_performer_images(str(performer["id"])) or []
    except Exception as e:
        logger.debug("could not load reference images: %s", e)
        return []
    primary = [i["url"] for i in imgs if i.get("is_primary") and i.get("url")]
    if primary:
        return primary[:1]
    any_url = [i["url"] for i in imgs if i.get("url")]
    return any_url[:1]


# ---------------------------------------------------------------------------
# Emit helpers (CLI-only)
# ---------------------------------------------------------------------------

def emit_json(path: str, performer: Dict[str, Any],
              records: List[ci.ImageRecord], licenses: List[str]) -> None:
    payload = {
        "performer_id": str(performer["id"]),
        "performer_name": performer["name"],
        "license_policy": ", ".join(licenses),
        "count": len(records),
        "images": [asdict(r) for r in records],
    }
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    logger.info("Wrote JSON: %s (%d images)", path, len(records))


def _sql_str(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def emit_sql(path: str, performer: Dict[str, Any],
             records: List[ci.ImageRecord]) -> None:
    pid = str(performer["id"])
    primary_idx = ci.primary_index(records)  # group photos never primary
    lines = [
        "-- Idempotent ingest of freely-licensed imagery into images + artist_images",
        f"-- Performer: {performer['name']} ({pid})",
        f"-- Generated by fetch_commons_images.py -- {len(records)} image(s)",
        "BEGIN;", "",
    ]
    for order, r in enumerate(records):
        f = r.db_fields()
        is_primary = "TRUE" if order == primary_idx else "FALSE"
        lines += [
            f"-- [{order}] {r.title or ''}  ({r.license_type})",
            "WITH img AS (",
            "    INSERT INTO images (",
            "        url, source, source_identifier, license_type, license_url,",
            "        attribution, width, height, thumbnail_url, source_page_url",
            "    ) VALUES (",
            "        {url}, {source}, {sid}, {lt}, {lu},".format(
                url=_sql_str(f["url"]), source=_sql_str(f["source"]),
                sid=_sql_str(f["source_identifier"]),
                lt=_sql_str(f["license_type"]), lu=_sql_str(f["license_url"])),
            "        {attr}, {w}, {h}, {thumb}, {page}".format(
                attr=_sql_str(f["attribution"]), w=_sql_str(f["width"]),
                h=_sql_str(f["height"]), thumb=_sql_str(f["thumbnail_url"]),
                page=_sql_str(f["source_page_url"])),
            "    )",
            "    ON CONFLICT (url) DO UPDATE SET updated_at = CURRENT_TIMESTAMP",
            "    RETURNING id",
            ")",
            "INSERT INTO artist_images (performer_id, image_id, is_primary, display_order)",
            f"SELECT {_sql_str(pid)}, id, {is_primary}, {order} FROM img",
            "ON CONFLICT (performer_id, image_id) DO NOTHING;", "",
        ]
    lines.append("COMMIT;")
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.info("Wrote SQL: %s (%d images)", path, len(records))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _config_from_args(args) -> ci.GatherConfig:
    return ci.GatherConfig(
        licenses=tuple(t.strip() for t in args.licenses.split(",") if t.strip()),
        include_nkcr=args.include_nkcr,
        recurse_subcats=args.recurse_subcats,
        portrait_filter=not args.no_portrait_filter,
        category=args.category,
        use_flickr=not args.no_flickr,
        flickr_licenses=args.flickr_licenses,
        limit=args.limit,
        visual=args.visual,
        reranker=args.reranker,
        do_rerank=not args.no_rerank,
        do_gate=not args.no_gate,
        identity=not args.no_identity,
        allow_faceless=args.allow_faceless,
        min_long_edge=args.min_long_edge,
        min_sharpness=args.min_sharpness,
        min_face_fraction=args.min_face_fraction,
        identity_threshold=args.identity_threshold,
        phash_distance=args.phash_distance,
        orb_dup_matches=args.orb_dup_matches,
        orb_dedup=not args.no_orb_dedup,
        rerank_cap=args.rerank_cap,
    )


def main() -> bool:
    script = ScriptBase(
        name="fetch_commons_images",
        description="Gather freely-licensed performer images from Wikimedia "
                    "Commons + Flickr Commons",
        epilog=__doc__,
    )
    g = script.parser.add_mutually_exclusive_group(required=True)
    g.add_argument("--name", help="Performer name")
    g.add_argument("--id", help="Performer UUID")

    script.add_dry_run_arg()
    script.add_debug_arg()
    p = script.parser
    p.add_argument("--limit", type=int, default=8)
    p.add_argument("--category", help="Commons category override (skips Wikidata)")
    p.add_argument("--recurse-subcats", type=int, default=0)
    p.add_argument("--licenses", default="public_domain,cc0,cc_by,cc_by_sa",
                   help="Accepted license_types (default free-culture set; "
                        "narrow to 'public_domain,cc0' for attribution-free)")
    p.add_argument("--include-nkcr", action="store_true")
    p.add_argument("--no-portrait-filter", action="store_true")
    p.add_argument("--flickr-licenses", default="4,5,9,10")
    p.add_argument("--no-flickr", action="store_true")
    p.add_argument("--no-db", action="store_true",
                   help="Do not touch the DB; requires --performer-id")
    p.add_argument("--performer-id", help="Performer UUID when --no-db is set")
    p.add_argument("--emit-json", help="Write candidate images to this JSON path")
    p.add_argument("--emit-sql", help="Write idempotent ingest SQL to this path")

    vis = p.add_argument_group("visual analysis")
    vis.add_argument("--visual", action="store_true",
                     help="Enable face/sharpness/identity gate, de-dup, rerank")
    vis.add_argument("--reranker", default="claude", choices=["claude", "clip"])
    vis.add_argument("--no-rerank", action="store_true")
    vis.add_argument("--no-gate", action="store_true")
    vis.add_argument("--no-identity", action="store_true")
    vis.add_argument("--reference-image",
                     help="URL of a known-good face for identity matching "
                          "(default: the performer's current primary image)")
    vis.add_argument("--allow-faceless", action="store_true")
    vis.add_argument("--min-long-edge", type=int, default=500)
    vis.add_argument("--min-sharpness", type=float, default=40.0)
    vis.add_argument("--min-face-fraction", type=float, default=0.015)
    vis.add_argument("--identity-threshold", type=float, default=0.60)
    vis.add_argument("--phash-distance", type=int, default=6)
    vis.add_argument("--orb-dup-matches", type=int, default=40)
    vis.add_argument("--no-orb-dedup", action="store_true")
    vis.add_argument("--rerank-cap", type=int, default=50,
                     help="Max images sent to the vision reranker (cost bound)")

    args = script.parse_args()
    config = _config_from_args(args)
    script.print_header({"DRY RUN": args.dry_run, "NO DB": args.no_db})

    # Resolve performer
    if args.no_db:
        if not args.name and not args.performer_id:
            logger.error("--no-db needs --name and --performer-id")
            return False
        performer = {
            "id": args.performer_id or "00000000-0000-0000-0000-000000000000",
            "name": normalize_apostrophes(args.name) if args.name else "(unknown)",
            "wikipedia_url": None,
        }
    else:
        performer = (find_performer_by_name(normalize_apostrophes(args.name))
                     if args.name else find_performer_by_id(args.id))
        if not performer:
            logger.error("Performer not found: %s", args.name or args.id)
            return False
    logger.info("Performer: %s (%s)", performer["name"], performer["id"])

    session = ci.make_session()
    records = ci.gather_candidates(
        performer["name"], performer.get("wikipedia_url"),
        session=session, config=config)

    if config.visual:
        logger.info("Running visual analysis on %d candidate(s) (reranker=%s)...",
                    len(records), "off" if args.no_rerank else args.reranker)
        ref_urls = _reference_urls(performer, args.reference_image,
                                   args.no_db, config.identity)
        records = ci.analyze_and_rank(
            records, session=session, config=config,
            reference_urls=ref_urls, performer_name=performer["name"])

    records = records[: config.limit]

    # Report
    logger.info("")
    logger.info("Candidate images (%d):", len(records))
    for i, r in enumerate(records):
        score = "" if r.quality_score is None else f" score={r.quality_score:5.1f}"
        logger.info("  [%d] %-18s %-13s%s %s", i, r.source, r.license_type,
                    score, (r.title or r.url)[:60])
        logger.info("        page: %s", r.source_page_url)
        logger.info("        attr: %s", r.attribution)
        if r.analysis and r.analysis.get("reasons"):
            logger.info("        gate: %s", "; ".join(r.analysis["reasons"]))
        if r.analysis and r.analysis.get("vision"):
            v = r.analysis["vision"]
            logger.info("        vision: q=%s subject=%s photo=%s %s",
                        v.get("quality"), v.get("is_subject"),
                        v.get("is_photograph"), v.get("rationale", ""))

    if args.emit_json:
        emit_json(args.emit_json, performer, records, list(config.licenses))
    if args.emit_sql:
        emit_sql(args.emit_sql, performer, records)

    saved = 0
    if records and not args.dry_run and not args.no_db:
        had_any = bool(get_performer_images(str(performer["id"])) or [])
        result = ci.persist_images(str(performer["id"]), records,
                                   had_any_image=had_any)
        saved = result["saved"]
        if not had_any and not result["primary_set"]:
            logger.warning("No single-subject portrait -> no primary image set")
    elif args.dry_run:
        logger.info("[DRY RUN] would save %d image(s)", len(records))

    script.print_summary({
        "candidates_kept": len(records),
        "saved_to_db": saved,
    })
    return True


if __name__ == "__main__":
    run_script(main)
