"""
YouTube candidate scoring.

Two modes, set by the caller based on whether we have a known recording
duration from MusicBrainz:

- `score_with_duration`: hard-reject candidates whose duration is outside
  ±3s of the known duration, then score by title/artist similarity with a
  channel-quality bonus. This is the high-confidence path — MB duration +
  YT video duration is a strong match signal.

- `score_conservative`: used when we DON'T know the recording duration.
  Stricter rules: require channel to be a "- Topic" channel OR to have
  ≥80% similarity to the expected artist name. Title must substring-match
  the normalized song title. Duration must be a sane range (30s-15min).

Uses the title/artist normalization + similarity primitives from
integrations.spotify.matching — they're service-agnostic.
"""

import re
from typing import Any, Dict, List, Optional, Tuple

from integrations.spotify.matching import (
    calculate_similarity,
    extract_primary_artist,
    is_substring_title_match,
    normalize_for_comparison,
    strip_ensemble_suffix,
)


# Delimiters we split on to break a collaboration credit into individual
# artists. A Topic channel may belong to any one of them, so we score
# against each and take the best.
_COLLABORATOR_SPLIT_RE = re.compile(
    r'\s*(?:&|,|/| and | feat\.? | featuring | with )\s*',
    flags=re.IGNORECASE,
)


def split_collaborators(artist: str) -> List[str]:
    """
    Break 'Frank Sinatra & Antônio Carlos Jobim' into ['Frank Sinatra',
    'Antônio Carlos Jobim']. Single-artist strings return a list of one.
    Empty input returns []. Strips whitespace + drops empties.
    """
    if not artist:
        return []
    parts = _COLLABORATOR_SPLIT_RE.split(artist)
    return [p.strip() for p in parts if p and p.strip()]


# Hard tolerance on duration match when we have MB ground truth (± 3 seconds).
DURATION_MATCH_WINDOW_MS = 3000

# "Artist - Topic" channels are auto-generated by YouTube Music from labels.
# They're the cleanest signal for "this is a real studio recording."
TOPIC_SUFFIX = ' - Topic'

# Sanity filter when we don't have duration ground truth.
CONSERVATIVE_MIN_MS = 30 * 1000
CONSERVATIVE_MAX_MS = 15 * 60 * 1000

# Accept thresholds. Confidence is 0.0-1.0; candidates below these floors are
# rejected even in their own mode.
MIN_CONFIDENCE_DURATION_MODE = 0.55
MIN_CONFIDENCE_CONSERVATIVE_MODE = 0.70


def is_topic_channel(channel_title: str) -> bool:
    """True for 'Bill Evans - Topic' style auto-generated channels."""
    return bool(channel_title) and channel_title.endswith(TOPIC_SUFFIX)


def topic_channel_artist(channel_title: str) -> Optional[str]:
    """Strip the trailing ' - Topic' to recover the artist name, or None."""
    if is_topic_channel(channel_title):
        return channel_title[:-len(TOPIC_SUFFIX)]
    return None


def _title_similarity(song_title: str, video_title: str) -> float:
    """
    Max similarity between normalized song title and video title.

    YT video titles almost always contain extra cruft — artist name, year,
    album name, "(Official Audio)", "Remastered 2014", etc. A raw whole-
    string similarity punishes this noise. So we also check substring-match
    as a fallback.
    """
    norm_song = normalize_for_comparison(song_title)
    norm_video = normalize_for_comparison(video_title or '')

    whole = calculate_similarity(norm_song, norm_video)
    if is_substring_title_match(norm_song, norm_video):
        # Substring match is a stronger signal than whole-string similarity
        # when the video title has extra tokens (year, album, etc).
        return max(whole, 85.0)
    return whole


def _artist_signal(expected_artist: str, channel_title: str, video_title: str) -> Tuple[float, str]:
    """
    Score how well a candidate's artist signal matches the expected artist.

    Returns (similarity_0_100, signal_label) where signal_label is one of:
    - 'topic'      — channel is "Expected - Topic" (best)
    - 'channel'    — channel name similar to expected artist
    - 'title'      — artist appears in video title
    - 'none'
    """
    norm_expected = normalize_for_comparison(expected_artist or '')
    if not norm_expected:
        return (0.0, 'none')

    # The channel could plausibly match the whole credit, the primary, the
    # ensemble-stripped form, OR any single collaborator ("A & B" may be on
    # "A - Topic" or "B - Topic"). Build the list of acceptable targets.
    targets = {expected_artist}
    primary = extract_primary_artist(expected_artist)
    if primary:
        targets.add(primary)
    stripped = strip_ensemble_suffix(expected_artist)
    if stripped:
        targets.add(stripped)
    for c in split_collaborators(expected_artist):
        targets.add(c)
        # The ensemble-stripped form of each collaborator too
        # (e.g. "Bill Evans Trio" → "Bill Evans")
        stripped_c = strip_ensemble_suffix(c)
        if stripped_c:
            targets.add(stripped_c)
    norm_targets = [normalize_for_comparison(t) for t in targets if t]

    # Topic channel — strongest signal.
    topic_artist = topic_channel_artist(channel_title or '')
    if topic_artist:
        norm_topic = normalize_for_comparison(topic_artist)
        topic_sim = max(
            (calculate_similarity(norm_topic, t) for t in norm_targets),
            default=0.0,
        )
        if topic_sim >= 75:
            return (topic_sim, 'topic')

    # Plain channel name similarity — best fit across all acceptable targets.
    norm_channel = normalize_for_comparison(channel_title or '')
    channel_sim = max(
        (calculate_similarity(norm_channel, t) for t in norm_targets),
        default=0.0,
    )
    if channel_sim >= 60:
        return (channel_sim, 'channel')

    # Artist in video title (user uploads often say "Artist - Title (...)")
    title_sim = calculate_similarity(
        normalize_for_comparison(video_title or ''),
        norm_expected,
    )
    # For this to count we need a substring hit, not just fuzzy:
    if is_substring_title_match(norm_expected, normalize_for_comparison(video_title or '')):
        return (max(title_sim, 70.0), 'title')

    return (max(channel_sim, title_sim), 'none')


def score_with_duration(
    candidate: Dict[str, Any],
    song_title: str,
    expected_artist: str,
    expected_duration_ms: int,
) -> Tuple[Optional[float], Dict[str, Any]]:
    """
    Duration-anchored scoring. Returns (confidence, detail). confidence is
    None if hard-rejected; detail has all the individual signals for logging.
    """
    detail: Dict[str, Any] = {
        'video_id': candidate.get('videoId'),
        'video_title': candidate.get('title'),
        'channel': candidate.get('channelTitle'),
        'duration_ms': candidate.get('duration_ms'),
        'rejected_reason': None,
    }

    cand_duration = candidate.get('duration_ms')
    if cand_duration is None:
        detail['rejected_reason'] = 'no_duration'
        return (None, detail)

    duration_diff = abs(cand_duration - expected_duration_ms)
    detail['duration_diff_ms'] = duration_diff
    if duration_diff > DURATION_MATCH_WINDOW_MS:
        detail['rejected_reason'] = f'duration_off_by_{duration_diff}ms'
        return (None, detail)

    title_sim = _title_similarity(song_title, candidate.get('title') or '')
    detail['title_sim'] = title_sim

    artist_sim, artist_signal = _artist_signal(
        expected_artist,
        candidate.get('channelTitle') or '',
        candidate.get('title') or '',
    )
    detail['artist_sim'] = artist_sim
    detail['artist_signal'] = artist_signal

    # Confidence: title 50%, artist 40%, duration-match bonus 10%.
    # Duration bonus is graded — ±0ms gets full 10%, ±3000ms gets 0%.
    duration_bonus = (1.0 - duration_diff / DURATION_MATCH_WINDOW_MS) * 0.10
    topic_bonus = 0.05 if artist_signal == 'topic' else 0.0
    confidence = (
        (title_sim / 100.0) * 0.50
        + (artist_sim / 100.0) * 0.40
        + duration_bonus
        + topic_bonus
    )
    confidence = min(confidence, 1.0)
    detail['confidence'] = confidence

    if confidence < MIN_CONFIDENCE_DURATION_MODE:
        detail['rejected_reason'] = f'below_threshold_{confidence:.2f}'
        return (None, detail)

    return (confidence, detail)


def score_conservative(
    candidate: Dict[str, Any],
    song_title: str,
    expected_artist: str,
) -> Tuple[Optional[float], Dict[str, Any]]:
    """
    Used when we have no MB duration. Stricter rules:
    - Channel must be Topic OR similar to expected artist (≥80%), OR the
      artist must appear substring-style in the video title.
    - Title must substring-contain the normalized song title.
    - Duration must be in a sane range (30s-15min).
    """
    detail: Dict[str, Any] = {
        'video_id': candidate.get('videoId'),
        'video_title': candidate.get('title'),
        'channel': candidate.get('channelTitle'),
        'duration_ms': candidate.get('duration_ms'),
        'rejected_reason': None,
    }

    cand_duration = candidate.get('duration_ms')
    if cand_duration is None or cand_duration < CONSERVATIVE_MIN_MS or cand_duration > CONSERVATIVE_MAX_MS:
        detail['rejected_reason'] = f'duration_out_of_range_{cand_duration}'
        return (None, detail)

    norm_song = normalize_for_comparison(song_title)
    norm_video_title = normalize_for_comparison(candidate.get('title') or '')
    if not is_substring_title_match(norm_song, norm_video_title):
        detail['rejected_reason'] = 'song_title_not_in_video_title'
        return (None, detail)

    artist_sim, artist_signal = _artist_signal(
        expected_artist,
        candidate.get('channelTitle') or '',
        candidate.get('title') or '',
    )
    detail['artist_sim'] = artist_sim
    detail['artist_signal'] = artist_signal

    # Conservative mode requires Topic or strong channel match, OR strong
    # artist-in-title signal.
    if artist_signal not in ('topic', 'channel') and artist_sim < 80:
        detail['rejected_reason'] = f'artist_signal_weak_{artist_signal}_{artist_sim:.0f}'
        return (None, detail)

    title_sim = _title_similarity(song_title, candidate.get('title') or '')
    detail['title_sim'] = title_sim

    # Confidence: title 45%, artist 50%, topic-channel bonus 5%.
    topic_bonus = 0.05 if artist_signal == 'topic' else 0.0
    confidence = (
        (title_sim / 100.0) * 0.45
        + (artist_sim / 100.0) * 0.50
        + topic_bonus
    )
    confidence = min(confidence, 1.0)
    detail['confidence'] = confidence

    if confidence < MIN_CONFIDENCE_CONSERVATIVE_MODE:
        detail['rejected_reason'] = f'below_threshold_{confidence:.2f}'
        return (None, detail)

    return (confidence, detail)


def pick_best(
    candidates: List[Dict[str, Any]],
    song_title: str,
    expected_artist: str,
    expected_duration_ms: Optional[int],
) -> Tuple[Optional[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Run every candidate through the appropriate scorer, return the best
    accepted one (if any) + the full list of per-candidate details for logs.
    """
    if expected_duration_ms:
        scorer = lambda c: score_with_duration(c, song_title, expected_artist, expected_duration_ms)
    else:
        scorer = lambda c: score_conservative(c, song_title, expected_artist)

    scored: List[Dict[str, Any]] = []
    best: Optional[Dict[str, Any]] = None
    best_conf: float = -1

    for cand in candidates:
        conf, detail = scorer(cand)
        scored.append(detail)
        if conf is not None and conf > best_conf:
            best_conf = conf
            best = {**cand, '_match_confidence': conf, '_match_detail': detail}

    return best, scored
